name: CheckDocsOnly

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:
  check_docs_only:
    name: check_docs_only
    runs-on: ubuntu-18.04
    outputs:
      skip: ${{ steps.check_docs_only.outputs.skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_docs_only
        # Since PR's are squashed prior to merging to the branch checked out (default branch),
        # HEAD^ will resolve to the previous point in history.
        run: |
          REF="HEAD^"
          [[ -z "${{ github.base_ref }}" ]] || REF=$(git show-ref ${{ github.base_ref }} | head -1 | cut -d' ' -f2)
          echo "::set-output name=skip::$(test/check-docs-only.sh $REF)" > .github/workflows/check.txt
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: check
          path: .github/workflows

  check:
    name: check
    runs-on: ubuntu-18.04
    needs: check_docs_only
    outputs:
      skip: cat .github/workflows/check.txt
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: check
          path: .github/workflows

      - run: echo "$(<.github/workflows/check.txt )"
